### ISSUE TITLE
大佬你好 请问你在atlas 编译中有遇到这个报错吗

### ISSUE THREAD

**Issue by chachabu** [Jiezhi/docker-cdh-repo#1]
Failed to execute goal org.apache.maven.plugins:maven-remote-resources-plugin:1.5:process (default) on project atlas-graphdb-janus: Error resolving project artifact: Could not transfer artifact com.sleepycat:je:pom:7.4.5 from/to typesafe (http://repo.typesafe.com/typesafe/releases/): Transfer failed for http://repo.typesafe.com/typesafe/releases/com/sleepycat/je/7.4.5/je-7.4.5.pom for project com.sleepycat:je:jar:7.4.5: Connect to repo.typesafe.com:80 [repo.typesafe.com/3.227.151.163, repo.typesafe.com/34.193.5.230, repo.typesafe.com/34.202.110.138] failed: Connection refused (Connection refused) -> [Help 1] 

这应该是插件的远程地址有问题 。但是这个地址我实在没有找到 问下大佬你编译的时候有这个报错么 ？或者你的mvn是什么样的 有什么改动

**Comment by Jiezhi** [comment]
还没遇到过这个问题，当时我编译这个atlas 只遇到 maven 版本低的问题 https://jiezhi.github.io/2020/03/31/atlas2-cdh6-hive-hook/ 。

你换阿里云的 repo 地址试试呢。
