### ISSUE TITLE
cdh 6.3.2 version was not builded on docker hub

### ISSUE THREAD

**Issue by mkkat** [Jiezhi/docker-cdh-repo#4]
Hi, I was looking for ubuntu1804-cdh-6.3.2 and finally found this repo.
but, there is no image on [docker hub](https://hub.docker.com/r/lencent/cdh/tags) (6.3.1 only exists).
How can I get the image?

**Comment by Jiezhi** [comment]
Sorry, it seems Cloudera doesn't support access to the repo for free user any more.

I can't build the CDH 6.3.2 to Docker.
